/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class com_example_houshuai_opencvjnidemo_dynamic_DynamicJni */

#ifndef _Included_com_example_houshuai_opencvjnidemo_dynamic_DynamicJni
#define _Included_com_example_houshuai_opencvjnidemo_dynamic_DynamicJni

#include "lang.h"
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_houshuai_opencvjnidemo_dynamic_DynamicJni
 * Method:    dynamicDetect
 * Signature: ([BII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_houshuai_opencvjnidemo_dynamic_DynamicJni_dynamicDetect
        (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
