/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef _Included_com_example_houshuai_opencvjnidemo_int_state_IntJni
#define _Included_com_example_houshuai_opencvjnidemo_int_state_IntJni
/* Header for class com_example_houshuai_opencvjnidemo_int_state_IntJni */
#include <opencv2/core.hpp>
#include <opencv2/objdetect.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <jni.h>
#include <string>
#include <stdlib.h>
#include "log.h"
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_houshuai_opencvjnidemo_int_state_IntJni
 * Method:    intDetect
 * Signature: ([IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_houshuai_opencvjnidemo_int_1state_IntJni_intDetect
  (JNIEnv *, jobject, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
