/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class com_example_houshuai_opencvjnidemo_state_StateJni */




#ifndef _Included_com_example_houshuai_opencvjnidemo_state_StateJni
#define _Included_com_example_houshuai_opencvjnidemo_state_StateJni
#include "lang.h"
#include <opencv2/core.hpp>
#include <opencv2/objdetect.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_houshuai_opencvjnidemo_state_StateJni
 * Method:    dealStateImage
 * Signature: (Ljava/lang/Object;I)V
 */
JNIEXPORT jintArray  JNICALL Java_com_example_houshuai_opencvjnidemo_bitmap_1state_BitmapStateJni_dealStateImage
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
